[package]
name = "kernel"
version = "0.1.0"
authors = ["Andrew Jianzhong Liu <liujzh@shanghaitech.edu.cn>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = "0.1.0"
rlibc = "0.1.4"
spin = "0.4.5"

[profile.release]
panic = "abort"